---
- name: Creating a key pair
  os_keypair:
    state: "{{ state }}"
    auth:
      username: "{{ auth_username }}"
      password: "{{ auth_password }}"
      project_name: "{{ auth_project }}"
    name: "{{ key_name }}"
    public_key_file: "{{ key_file }}" 
