---
- name: Creating a security group
  os_security_group:
    state: "{{ state }}"
    auth:
      username: "{{ auth_username }}"
      password: "{{ auth_password }}"
      project_name: "{{ auth_project }}"
    name: "{{ sec_group_name }}"
