---
- name: Rule to allow port 80 on inbound
  os_security_group_rule:
    state: "{{ state }}"
    security_group: "{{ http_sec_group }}"
    auth:
      username: "{{ auth_username }}"
      password: "{{ auth_password }}"
      project_name: "{{ auth_project }}"
    direction: ingress
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

