---
- name: Rule to allow port 443 on inbound
  os_security_group_rule:
    state: "{{ state }}"
    auth:
      username: "{{ auth_username }}"
      password: "{{ auth_password }}"
      project_name: "{{ auth_project }}"
    security_group: "{{ https_sec_group }}"
    direction: ingress
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

